// utils/citySlugData.ts
// SEO-optimized city data for dynamic /mutari/[city] pages

export interface CityData {
  slug: string;
  name: string;
  county: string;
  population: string;
  tier: 1 | 2;
  landmarks: string[];
  neighborhoods: string[];
  metaDescription: string;
  heroSubtitle: string;
}

// Helper to create URL-friendly slugs from Romanian city names
export function slugify(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // Remove diacritics
    .replace(/ș/g, "s")
    .replace(/ț/g, "t")
    .replace(/ă/g, "a")
    .replace(/â/g, "a")
    .replace(/î/g, "i")
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");
}

export const cityData: CityData[] = [
  // Tier 1 - Major Cities (10)
  {
    slug: "bucuresti",
    name: "București",
    county: "București",
    population: "2.100.000",
    tier: 1,
    landmarks: ["Palatul Parlamentului", "Centrul Vechi", "Parcul Herăstrău"],
    neighborhoods: ["Militari", "Drumul Taberei", "Titan", "Berceni", "Pipera", "Dorobanți"],
    metaDescription: "Servicii de mutări în București ✓ Compară 3-5 oferte gratuite de la firme verificate ✓ Economisește până la 40% ✓ Transport mobilă în toate sectoarele",
    heroSubtitle: "Capitala României merită firme de mutări de top. Primește oferte personalizate pentru mutarea ta în București.",
  },
  {
    slug: "cluj-napoca",
    name: "Cluj-Napoca",
    county: "Cluj",
    population: "324.000",
    tier: 1,
    landmarks: ["Piața Unirii", "Cetățuia", "Grădina Botanică"],
    neighborhoods: ["Mărăști", "Gheorgheni", "Mănăștur", "Zorilor", "Bună Ziua", "Borhanci"],
    metaDescription: "Mutări în Cluj-Napoca ✓ 3-5 oferte GRATUITE în 24h ✓ Firme verificate ✓ Transport mobilă, împachetare, depozitare ✓ Economisește 40%",
    heroSubtitle: "Inima Transilvaniei, centru universitar și IT. Mutări profesionale pentru clujeni exigenți.",
  },
  {
    slug: "timisoara",
    name: "Timișoara",
    county: "Timiș",
    population: "319.000",
    tier: 1,
    landmarks: ["Piața Victoriei", "Piața Unirii", "Parcul Rozelor"],
    neighborhoods: ["Fabric", "Iosefin", "Lipovei", "Girocului", "Dâmbovița", "Aradului"],
    metaDescription: "Firme de mutări Timișoara ✓ Compară oferte gratuite ✓ Transport mobilă în tot Banatul ✓ Servicii complete: împachetare, demontare, depozitare",
    heroSubtitle: "Capitala Banatului, Capitală Culturală Europeană. Servicii de mutări la standarde europene.",
  },
  {
    slug: "iasi",
    name: "Iași",
    county: "Iași",
    population: "382.000",
    tier: 1,
    landmarks: ["Palatul Culturii", "Grădina Copou", "Universitatea Al.I. Cuza"],
    neighborhoods: ["Copou", "Păcurari", "Alexandru cel Bun", "Galata", "Nicolina", "Tătărași"],
    metaDescription: "Mutări Iași ✓ 3-5 oferte în 24h de la firme locale verificate ✓ 100% gratuit ✓ Transport mobilă în Moldova ✓ Economii până la 40%",
    heroSubtitle: "Capitala Moldovei, oraș universitar. Mutări rapide și sigure pentru ieșeni.",
  },
  {
    slug: "constanta",
    name: "Constanța",
    county: "Constanța",
    population: "283.000",
    tier: 1,
    landmarks: ["Cazinoul", "Portul Tomis", "Delfinariul"],
    neighborhoods: ["Tomis", "Mamaia", "Palazu Mare", "Compozitorilor", "Km 4-5", "Poarta 6"],
    metaDescription: "Servicii mutări Constanța ✓ Transport mobilă pe litoral ✓ Oferte gratuite de la firme verificate ✓ Mutări apartamente și case",
    heroSubtitle: "Perlă la Marea Neagră. Mutări profesionale pentru locuitorii litoralului.",
  },
  {
    slug: "brasov",
    name: "Brașov",
    county: "Brașov",
    population: "253.000",
    tier: 1,
    landmarks: ["Biserica Neagră", "Tâmpa", "Piața Sfatului"],
    neighborhoods: ["Astra", "Tractorul", "Răcădău", "Bartolomeu", "Scriitorilor", "Noua"],
    metaDescription: "Mutări Brașov ✓ Firme verificate pentru transport mobilă ✓ Compară 3-5 oferte GRATUIT ✓ Servicii în tot județul și stațiuni",
    heroSubtitle: "La poalele Tâmpei, în inima munților. Mutări sigure pentru brașoveni.",
  },
  {
    slug: "craiova",
    name: "Craiova",
    county: "Dolj",
    population: "269.000",
    tier: 1,
    landmarks: ["Parcul Nicolae Romanescu", "Teatrul Național", "Universitatea"],
    neighborhoods: ["Craiovița Nouă", "Brazda lui Novac", "Romanești", "1 Mai", "Lăpuș", "Centru"],
    metaDescription: "Firme mutări Craiova ✓ Transport mobilă în Oltenia ✓ Oferte gratuite în 24h ✓ Servicii complete pentru apartamente și case",
    heroSubtitle: "Capitala Olteniei, centru economic în sud. Mutări de încredere pentru craioveni.",
  },
  {
    slug: "galati",
    name: "Galați",
    county: "Galați",
    population: "249.000",
    tier: 1,
    landmarks: ["Dunărea", "Grădina Publică", "Complexul Muzeal"],
    neighborhoods: ["Micro", "Țiglina", "Mazepa", "Dunărea", "Centru", "Siderurgiștilor"],
    metaDescription: "Mutări Galați ✓ Transport mobilă pe Dunăre ✓ Compară oferte gratuite de la firme locale ✓ Economisește până la 40%",
    heroSubtitle: "Oraș portuar pe Dunăre, inimă industrială. Mutări rapide în Galați și împrejurimi.",
  },
  {
    slug: "oradea",
    name: "Oradea",
    county: "Bihor",
    population: "196.000",
    tier: 1,
    landmarks: ["Cetatea Oradea", "Piața Unirii", "Băile Felix"],
    neighborhoods: ["Rogerius", "Nufărul", "Ioșia", "Velența", "Decebal", "Centru"],
    metaDescription: "Servicii mutări Oradea ✓ Firme verificate în Bihor ✓ Transport mobilă către Ungaria și Europa ✓ Oferte gratuite",
    heroSubtitle: "Poartă spre Europa, bijuterie Art Nouveau. Mutări la nivel european pentru orădeni.",
  },
  {
    slug: "ploiesti",
    name: "Ploiești",
    county: "Prahova",
    population: "209.000",
    tier: 1,
    landmarks: ["Ceasul din centru", "Parcul Bucov", "Halele Centrale"],
    neighborhoods: ["Nord", "Sud", "Vest", "Malu Roșu", "Bereasca", "9 Mai"],
    metaDescription: "Mutări Ploiești ✓ Transport mobilă în Prahova ✓ Compară 3-5 oferte GRATUIT ✓ Firme verificate pentru mutări sigure",
    heroSubtitle: "Capitala aurului negru, la porțile munților. Mutări profesionale pentru ploieșteni.",
  },

  // Tier 2 - County Capitals (32)
  {
    slug: "alba-iulia",
    name: "Alba Iulia",
    county: "Alba",
    population: "74.000",
    tier: 2,
    landmarks: ["Cetatea Alba Carolina", "Catedrala Încoronării"],
    neighborhoods: ["Cetate", "Ampoi", "Pâclișa", "Micești"],
    metaDescription: "Mutări Alba Iulia ✓ Transport mobilă în județul Alba ✓ Oferte gratuite de la firme locale verificate",
    heroSubtitle: "Cetate istorică, capitală a Marii Uniri. Mutări de încredere în Alba.",
  },
  {
    slug: "arad",
    name: "Arad",
    county: "Arad",
    population: "159.000",
    tier: 2,
    landmarks: ["Palatul Administrativ", "Cetatea Arad", "Parcul Reconcilierii"],
    neighborhoods: ["Centru", "Subcetate", "Micalaca", "Aurel Vlaicu", "Grădiste"],
    metaDescription: "Firme mutări Arad ✓ Transport mobilă în Vest ✓ Compară oferte gratuite ✓ Mutări către Ungaria și Europa",
    heroSubtitle: "Poartă vestică a României. Mutări profesionale pentru arădeni.",
  },
  {
    slug: "pitesti",
    name: "Pitești",
    county: "Argeș",
    population: "155.000",
    tier: 2,
    landmarks: ["Parcul Trivale", "Primărie", "Bascov"],
    neighborhoods: ["Nord", "Sud", "Găvana", "Craiovei", "Exercițiu"],
    metaDescription: "Mutări Pitești ✓ Transport mobilă în Argeș ✓ Oferte gratuite în 24h ✓ Firme verificate",
    heroSubtitle: "Capitală auto a României, la poalele Carpaților. Mutări rapide în Pitești.",
  },
  {
    slug: "bacau",
    name: "Bacău",
    county: "Bacău",
    population: "144.000",
    tier: 2,
    landmarks: ["Teatrul Bacovia", "Parcul Cancicov", "Centrul Vechi"],
    neighborhoods: ["Centru", "Ștefan cel Mare", "Cornișa", "Sud", "Miorița"],
    metaDescription: "Servicii mutări Bacău ✓ Transport mobilă în Moldova ✓ Compară oferte gratuite de la firme locale",
    heroSubtitle: "În inima Moldovei, oraș în dezvoltare. Mutări de calitate pentru băcăuani.",
  },
  {
    slug: "bistrita",
    name: "Bistrița",
    county: "Bistrița-Năsăud",
    population: "75.000",
    tier: 2,
    landmarks: ["Turnul Bisericii Evanghelice", "Piața Centrală", "Codrișor"],
    neighborhoods: ["Centru", "Viișoara", "Unirea", "Subcetate"],
    metaDescription: "Mutări Bistrița ✓ Transport mobilă în nord-vestul Transilvaniei ✓ Oferte gratuite de la firme verificate",
    heroSubtitle: "Ținutul lui Dracula, frumusețe transilvăneană. Mutări sigure în Bistrița.",
  },
  {
    slug: "botosani",
    name: "Botoșani",
    county: "Botoșani",
    population: "106.000",
    tier: 2,
    landmarks: ["Centrul Vechi", "Parcul Mihai Eminescu", "Memorial Eminescu"],
    neighborhoods: ["Centru", "Imparat Traian", "Bucovina", "Plevna"],
    metaDescription: "Firme mutări Botoșani ✓ Transport mobilă în nordul Moldovei ✓ Compară oferte gratuite",
    heroSubtitle: "Plaiuri eminesciene, tradiție și cultură. Mutări profesionale în Botoșani.",
  },
  {
    slug: "braila",
    name: "Brăila",
    county: "Brăila",
    population: "168.000",
    tier: 2,
    landmarks: ["Faleza Dunării", "Piața Traian", "Teatrul Maria Filotti"],
    neighborhoods: ["Centru", "Viziru", "Radu Negru", "Chercea", "Apollo"],
    metaDescription: "Mutări Brăila ✓ Transport mobilă pe Dunăre ✓ Oferte gratuite în 24h ✓ Firme locale verificate",
    heroSubtitle: "Port dunărean, spirit pescaresc. Mutări de încredere în Brăila.",
  },
  {
    slug: "buzau",
    name: "Buzău",
    county: "Buzău",
    population: "115.000",
    tier: 2,
    landmarks: ["Parcul Crâng", "Episcopia", "Centrul Vechi"],
    neighborhoods: ["Centru", "Dorobanți", "Micro 14", "Broșteni"],
    metaDescription: "Servicii mutări Buzău ✓ Transport mobilă în Muntenia ✓ Compară oferte gratuite de la firme verificate",
    heroSubtitle: "La răscruce de drumuri, tradiție și modernitate. Mutări sigure în Buzău.",
  },
  {
    slug: "resita",
    name: "Reșița",
    county: "Caraș-Severin",
    population: "73.000",
    tier: 2,
    landmarks: ["Muzeul Locomotivelor", "Secu", "Nera"],
    neighborhoods: ["Centru", "Govândari", "Mociur", "Stavila"],
    metaDescription: "Mutări Reșița ✓ Transport mobilă în Banat ✓ Oferte gratuite de la firme locale verificate",
    heroSubtitle: "Capitala fierului, în inima munților. Mutări profesionale în Reșița.",
  },
  {
    slug: "calarasi",
    name: "Călărași",
    county: "Călărași",
    population: "65.000",
    tier: 2,
    landmarks: ["Dunărea", "Parcul Central", "Lacul Iezer"],
    neighborhoods: ["Centru", "Măgureni", "Mircea Vodă", "Orizont"],
    metaDescription: "Firme mutări Călărași ✓ Transport mobilă în sudul României ✓ Compară oferte gratuite",
    heroSubtitle: "Pe malul Dunării, la granița cu Bulgaria. Mutări rapide în Călărași.",
  },
  {
    slug: "sfantu-gheorghe",
    name: "Sfântu Gheorghe",
    county: "Covasna",
    population: "56.000",
    tier: 2,
    landmarks: ["Cetatea Sfântu Gheorghe", "Parcul Central", "Muzeul Național"],
    neighborhoods: ["Centru", "Câmpul Frumos", "Simeria", "Ciucului"],
    metaDescription: "Mutări Sfântu Gheorghe ✓ Transport mobilă în Covasna ✓ Oferte gratuite în 24h",
    heroSubtitle: "Capitala Secuimii, tradiție și armonie. Mutări sigure în Sfântu Gheorghe.",
  },
  {
    slug: "targoviste",
    name: "Târgoviște",
    county: "Dâmbovița",
    population: "79.000",
    tier: 2,
    landmarks: ["Curtea Domnească", "Turnul Chindiei", "Parcul Chindia"],
    neighborhoods: ["Centru", "Micro", "Priseaca", "Matei Voievod"],
    metaDescription: "Servicii mutări Târgoviște ✓ Transport mobilă în Dâmbovița ✓ Compară oferte gratuite",
    heroSubtitle: "Vechea capitală a Țării Românești. Mutări de încredere în Târgoviște.",
  },
  {
    slug: "slobozia",
    name: "Slobozia",
    county: "Ialomița",
    population: "45.000",
    tier: 2,
    landmarks: ["Parcul Central", "Biserica Sfântul Nicolae", "Ialomița"],
    neighborhoods: ["Centru", "Bora", "Matei Basarab"],
    metaDescription: "Mutări Slobozia ✓ Transport mobilă în Ialomița ✓ Oferte gratuite de la firme verificate",
    heroSubtitle: "În Bărăgan, între București și Constanța. Mutări profesionale în Slobozia.",
  },
  {
    slug: "baia-mare",
    name: "Baia Mare",
    county: "Maramureș",
    population: "123.000",
    tier: 2,
    landmarks: ["Turnul lui Ștefan", "Piața Libertății", "Centrul Vechi"],
    neighborhoods: ["Centru", "Vasile Alecsandri", "Săsar", "Ferneziu", "Firiza"],
    metaDescription: "Firme mutări Baia Mare ✓ Transport mobilă în Maramureș ✓ Compară oferte gratuite în 24h",
    heroSubtitle: "Poartă către Maramureșul tradițional. Mutări de calitate în Baia Mare.",
  },
  {
    slug: "drobeta-turnu-severin",
    name: "Drobeta-Turnu Severin",
    county: "Mehedinți",
    population: "92.000",
    tier: 2,
    landmarks: ["Podul lui Traian", "Cetatea Severinului", "Dunărea"],
    neighborhoods: ["Centru", "Crihala", "Kiseleff", "Aluniș"],
    metaDescription: "Mutări Drobeta-Turnu Severin ✓ Transport mobilă în Mehedinți ✓ Oferte gratuite",
    heroSubtitle: "Unde Dunărea își face drum prin munți. Mutări sigure în Drobeta.",
  },
  {
    slug: "targu-mures",
    name: "Târgu Mureș",
    county: "Mureș",
    population: "134.000",
    tier: 2,
    landmarks: ["Palatul Culturii", "Cetatea Medievală", "Grădina Zoo"],
    neighborhoods: ["Centru", "Tudor", "Cornișa", "Unirii", "7 Noiembrie"],
    metaDescription: "Servicii mutări Târgu Mureș ✓ Transport mobilă în Transilvania ✓ Compară oferte gratuite",
    heroSubtitle: "Capitală culturală în inima țării. Mutări profesionale în Târgu Mureș.",
  },
  {
    slug: "piatra-neamt",
    name: "Piatra Neamț",
    county: "Neamț",
    population: "85.000",
    tier: 2,
    landmarks: ["Turnul lui Ștefan cel Mare", "Parcul Central", "Telecabina"],
    neighborhoods: ["Centru", "Precista", "Dărmănești", "Speranța"],
    metaDescription: "Mutări Piatra Neamț ✓ Transport mobilă în Neamț ✓ Oferte gratuite de la firme verificate",
    heroSubtitle: "La poalele munților, în inima naturii. Mutări de încredere în Piatra Neamț.",
  },
  {
    slug: "slatina",
    name: "Slatina",
    county: "Olt",
    population: "70.000",
    tier: 2,
    landmarks: ["Turnul de Apă", "Parcul Central", "Malul Oltului"],
    neighborhoods: ["Centru", "Steaua", "Crișan", "Primăverii"],
    metaDescription: "Firme mutări Slatina ✓ Transport mobilă în județul Olt ✓ Compară oferte gratuite",
    heroSubtitle: "Pe malul Oltului, centru industrial. Mutări rapide în Slatina.",
  },
  {
    slug: "satu-mare",
    name: "Satu Mare",
    county: "Satu Mare",
    population: "102.000",
    tier: 2,
    landmarks: ["Turnul Pompierilor", "Parcul Vasile Lucaciu", "Centrul Vechi"],
    neighborhoods: ["Centru", "Carpați", "Micro 17", "Solidarității"],
    metaDescription: "Mutări Satu Mare ✓ Transport mobilă în nord-vest ✓ Oferte gratuite în 24h ✓ Firme verificate",
    heroSubtitle: "În țara Oașului, la granița cu Ungaria. Mutări profesionale în Satu Mare.",
  },
  {
    slug: "zalau",
    name: "Zalău",
    county: "Sălaj",
    population: "56.000",
    tier: 2,
    landmarks: ["Ruinele Castrul Roman", "Parcul Central", "Meseș"],
    neighborhoods: ["Centru", "Dumbrava", "Ortelec", "Porolissum"],
    metaDescription: "Servicii mutări Zalău ✓ Transport mobilă în Sălaj ✓ Compară oferte gratuite",
    heroSubtitle: "Capitala Sălajului, istorie și natură. Mutări sigure în Zalău.",
  },
  {
    slug: "sibiu",
    name: "Sibiu",
    county: "Sibiu",
    population: "147.000",
    tier: 2,
    landmarks: ["Piața Mare", "Podul Minciunilor", "Casele cu Ochi"],
    neighborhoods: ["Centru Istoric", "Hipodrom", "Cibin", "Ștrand", "Turnișor"],
    metaDescription: "Mutări Sibiu ✓ Transport mobilă în Transilvania ✓ Oferte gratuite de la firme verificate ✓ Economisește 40%",
    heroSubtitle: "Bijuterie medievală, Capitală Culturală Europeană. Mutări premium în Sibiu.",
  },
  {
    slug: "suceava",
    name: "Suceava",
    county: "Suceava",
    population: "92.000",
    tier: 2,
    landmarks: ["Cetatea de Scaun", "Mănăstirile din Bucovina", "Parcul Central"],
    neighborhoods: ["Centru", "George Enescu", "Obcini", "Burdujeni"],
    metaDescription: "Firme mutări Suceava ✓ Transport mobilă în Bucovina ✓ Compară oferte gratuite în 24h",
    heroSubtitle: "Poartă către Bucovina, țara mănăstirilor. Mutări de încredere în Suceava.",
  },
  {
    slug: "alexandria",
    name: "Alexandria",
    county: "Teleorman",
    population: "45.000",
    tier: 2,
    landmarks: ["Parcul Central", "Primăria", "Centrul Civic"],
    neighborhoods: ["Centru", "Vedea", "Libertății"],
    metaDescription: "Mutări Alexandria ✓ Transport mobilă în Teleorman ✓ Oferte gratuite de la firme locale",
    heroSubtitle: "În câmpia Teleormanului, spirit agrar. Mutări profesionale în Alexandria.",
  },
  {
    slug: "tulcea",
    name: "Tulcea",
    county: "Tulcea",
    population: "73.000",
    tier: 2,
    landmarks: ["Deltă Dunării", "Monumentul Independenței", "Portul"],
    neighborhoods: ["Centru", "Piața Nouă", "Cima", "Vest"],
    metaDescription: "Servicii mutări Tulcea ✓ Transport mobilă în Dobrogea ✓ Compară oferte gratuite",
    heroSubtitle: "Poarta Deltei, paradis natural. Mutări sigure în Tulcea.",
  },
  {
    slug: "vaslui",
    name: "Vaslui",
    county: "Vaslui",
    population: "55.000",
    tier: 2,
    landmarks: ["Statuia lui Ștefan cel Mare", "Parcul Copou", "Centrul Istoric"],
    neighborhoods: ["Centru", "Traian", "Republicii", "Olteni"],
    metaDescription: "Mutări Vaslui ✓ Transport mobilă în Moldova ✓ Oferte gratuite de la firme verificate",
    heroSubtitle: "Locul victoriei lui Ștefan cel Mare. Mutări de încredere în Vaslui.",
  },
  {
    slug: "ramnicu-valcea",
    name: "Râmnicu Vâlcea",
    county: "Vâlcea",
    population: "98.000",
    tier: 2,
    landmarks: ["Barajul Vidraru", "Parcul Zăvoi", "Mănăstiri Oltenia"],
    neighborhoods: ["Centru", "Traian", "Nord", "Ostroveni"],
    metaDescription: "Firme mutări Râmnicu Vâlcea ✓ Transport mobilă în Vâlcea ✓ Compară oferte gratuite",
    heroSubtitle: "La poalele Carpaților, pe Valea Oltului. Mutări profesionale în Râmnicu Vâlcea.",
  },
  {
    slug: "focsani",
    name: "Focșani",
    county: "Vrancea",
    population: "79.000",
    tier: 2,
    landmarks: ["Mausoleul Unirii", "Parcul Bujorilor", "Centrul Vechi"],
    neighborhoods: ["Centru", "Sud", "Nord", "Vest"],
    metaDescription: "Mutări Focșani ✓ Transport mobilă în Vrancea ✓ Oferte gratuite în 24h",
    heroSubtitle: "Orașul Unirii, la confluența istoriei. Mutări sigure în Focșani.",
  },
  {
    slug: "deva",
    name: "Deva",
    county: "Hunedoara",
    population: "61.000",
    tier: 2,
    landmarks: ["Cetatea Deva", "Telecabina", "Parcul Cetate"],
    neighborhoods: ["Centru", "Bejan", "Micro", "Progresul"],
    metaDescription: "Servicii mutări Deva ✓ Transport mobilă în Hunedoara ✓ Compară oferte gratuite",
    heroSubtitle: "Sub cetatea medievală, capitală a aurului. Mutări de încredere în Deva.",
  },
  {
    slug: "miercurea-ciuc",
    name: "Miercurea Ciuc",
    county: "Harghita",
    population: "38.000",
    tier: 2,
    landmarks: ["Cetatea Mikó", "Parcul Central", "Pârtia de schi"],
    neighborhoods: ["Centru", "Topliței", "Jigodin"],
    metaDescription: "Mutări Miercurea Ciuc ✓ Transport mobilă în Harghita ✓ Oferte gratuite de la firme verificate",
    heroSubtitle: "În țara secuiască, la poalele Harghitei. Mutări profesionale în Miercurea Ciuc.",
  },
  {
    slug: "targu-jiu",
    name: "Târgu Jiu",
    county: "Gorj",
    population: "82.000",
    tier: 2,
    landmarks: ["Coloana Infinitului", "Poarta Sărutului", "Parcul Central"],
    neighborhoods: ["Centru", "Drăgoeni", "Tudor Vladimirescu", "Primăverii"],
    metaDescription: "Firme mutări Târgu Jiu ✓ Transport mobilă în Gorj ✓ Compară oferte gratuite în 24h",
    heroSubtitle: "Orașul lui Brâncuși, artă și tradiție. Mutări sigure în Târgu Jiu.",
  },
  {
    slug: "giurgiu",
    name: "Giurgiu",
    county: "Giurgiu",
    population: "54.000",
    tier: 2,
    landmarks: ["Turnul cu Ceas", "Dunărea", "Podul Prieteniei"],
    neighborhoods: ["Centru", "Dunărea", "Slobozia", "Giurgiu Nord"],
    metaDescription: "Mutări Giurgiu ✓ Transport mobilă la Dunăre ✓ Oferte gratuite ✓ Mutări către Bulgaria",
    heroSubtitle: "La poarta spre Bulgaria, port dunărean. Mutări rapide în Giurgiu.",
  },
];

// Get all city slugs for static paths
export function getAllCitySlugs(): string[] {
  return cityData.map((city) => city.slug);
}

// Get city data by slug
export function getCityBySlug(slug: string): CityData | undefined {
  return cityData.find((city) => city.slug === slug);
}

// Get top cities for footer/navigation
export function getTopCities(limit: number = 10): CityData[] {
  return cityData.filter((city) => city.tier === 1).slice(0, limit);
}
