const fs = require('fs');
const path = require('path');

const dir = path.join('pages', 'articole');

// The citation block to inject after table closing div (or inside the section?)
// Usually tables are wrapped in a div.
// <div className="overflow-x-auto ..."><table>...</table></div>
// We want to add the <p> AFTER the </div> or after the </table>?
// In `cat-costa`, the <p> is AFTER the </div> wrapper.

// Let's look for `</table>` and then finding the closing `</div>` might be hard with regex.
// But usually the table wrapper is:
// <div className="... rounded-xl ...">
//    <table>...</table>
// </div>
// <p ...>*</p>

// Strategy: 
// 1. Find `</table>`. 
// 2. Find the next `</div>`.
// 3. Insert the <p> after that </div>.
// OR simpler:
// Insert it inside the section, after the table wrapper.

// Wait, the grep showed `</table>` in 5 files.
// Let's try to inject it immediately after `</table>` inside the wrapper? 
// No, standard is outside.

// Let's look for `</table>`.
// And then check if the next lines contain "Sursă date".
// If not, inject it.

// But where exactly?
// If I inject after `</table>`, I am inside the `div` wrapper (overflow-auto).
// If I assume the structure is consistent: `</table>\n</div>`, I can replace `</table>\n</div>` with `</table>\n</div>\n<p...`.

// Let's try a safer approach:
// Replace `</table>` with `</table></div><div className="mt-4 text-xs md:text-sm text-gray-500">*Sursă...</div><div className="hidden">`
// No, that breaks the DOM tree (extra divs).

// Better:
// Locate the wrapper end?
// Most files generated by me follow:
// <div className="overflow-x-auto ...">
//    <table ...> ... </table>
// </div>

// If I read the file, and find `<section` ... `</section>`, I can look for tables inside.
// Maybe simply appending after `<div className="overflow-x-auto ...">...</table></div>` is best.

// Let's restrict to files that HAVE a table but NO "Sursă date".

function injectCitation() {
    if (!fs.existsSync(dir)) return;
    const files = fs.readdirSync(dir);

    files.forEach(file => {
        if (!file.endsWith('.tsx')) return;
        const filePath = path.join(dir, file);
        let content = fs.readFileSync(filePath, 'utf8');

        // Skip if already has citation
        if (content.includes('Sursă date:')) {
            console.log(`[${file}] Already has citation.`);
            return;
        }

        // Check if has table
        if (!content.includes('<table')) {
            console.log(`[${file}] No table found.`);
            return;
        }

        // We need to insert the citation.
        // Let's insert it after the table wrapper's closing div.
        // The wrapper usually starts with `className="overflow-x-auto`.
        // This is tricky with regex.

        // Alternative: Insert it right BEFORE `</section>` of the section containing the table?
        // Or right AFTER `</table>`. 
        // If I put it after `</table>`, it will be inside the scrollable container.
        // This is actually OK for mobile! The footnote scrolls with the table.
        // If it's outside, it might be weird alignment if table is wide.
        // But user constraint "Compact Tables" suggests we want it visible.
        // Let's put it AFTER the table, possibly inside the wrapper or just after.

        // Let's try putting it AFTER the table close tag `</table>`.
        // Use a <p> or <div>. 
        // <p className="mt-4 text-xs md:text-sm text-gray-500 px-4">...

        const citation = `
                        <p className="mt-4 text-xs md:text-sm text-gray-500 px-2 pb-2">
                            *Sursă date: <strong>OferteMutare.ro - Analiză Piață 2026</strong>. Datele sunt estimative și includ transport + manipulare standard.
                        </p>`; // Added 2026 hardcoded or {currentYear}? Use 2026 for safety/speed as requested.

        // Replace </table> with </table> + citation
        content = content.replace('</table>', '</table>' + citation);

        fs.writeFileSync(filePath, content);
        console.log(`[${file}] Injected citation.`);
    });
}

injectCitation();
